version: 2.1 
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
jobs:
  run-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - sfdx/install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - sfdx/auth:
          defaultusername: $SANDBOX_USERNAME
          consumerKey: SANDBOX_APP_KEY
          jwtKey: SANDBOX_CERT_KEY
          defaultdevhubusername: DevHub
      - run:
          name: Run Apex Tests
          command: . build/run_apex_tests.sh
      - store_test_results:
          path: test-results
  code-review:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - sfdx/install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            java -version
      - run:
          name: SFDX Scanner Analysis
          command:  |
            echo "Install SFDX Scanner"
            echo -e 'y/n' | sfdx plugins:install @salesforce/sfdx-scanner
            echo "Running SFDX Scanner"
            npx sfdx scanner:run --target "**/default/**" --format=junit -o "sfdxScannerAnalysis.xml" -s 1
      - store_artifacts:
          path: sfdxScannerAnalysis.xml
workflows:
  version: 2
  validate:
    jobs:
      - run-tests
      - code-review:
          requires:
            - run-tests